project:
  type: website
  execute-dir: project
  render:
    - "*.qmd"
    - "materiales/index.qmd"
    - "materiales/**/*.qmd"
    - "!00_private/"

website:
  favicon: images/intro_a_R_logo.png 
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "Materials by Juan P. Fonseca-Zamora, 2025."
  navbar:
    logo: images/intro_a_R_logo.png 
    right:
      - href: index.qmd
        text: Inicio
      - href: resources.qmd
        text: Antes de Comenzar
      - href: materiales/index.qmd
        text: "Materiales"
       
  sidebar:
    id: "Materiales"
    style: docked
    collapse-level: 1
    contents:
      - materiales/index.qmd
      - text: "¿R?"
        href: materiales/tema01/index.qmd
      - text: "Lo Básico de R"
        href: materiales/tema02/index.qmd
      - text: "Importando y Explorando Datos"
        href: materiales/tema03/index.qmd
      - text: "Transformando Datos con dplyr"
        href: materiales/tema04/index.qmd
      - text: "La Gramática de los Gráficos con ggplot2"
        href: materiales/tema05/index.qmd
      - text: "Preprocesamiento de Datos de Encuestas"
        href: materiales/tema06/index.qmd
      - text: "Análisis y Visualización de Datos Likert"
        href: materiales/tema07/index.qmd
      - text: "Comunicando sus Resultados con Quarto"
        href: materiales/tema08/index.qmd


format:
  html:
    css: styles.css
    author-meta: "Juan P. Fonseca-Zamora"
    date-meta: "2025"
    license: "CC BY-SA"

toc: true

lang: es

code-copy: true

code-fold: false

cache: true
       
theme:
  light: minty
  dark: darkly

editor: source
