project:
  type: website
  render:
    - "*.qmd"
    - "materiales/index.qmd"
    - "materiales/**/*.qmd"
    - "!00_private/"

website:
  title: "Introducción al Análisis de Datos con R"
  navbar: 
    right:
      - href: index.qmd
        text: Inicio
      - href: resources.qmd
        text: Antes de Comenzar
      - href: materiales/index.qmd
        text: "Materiales"
       
  sidebar:
    - id: "Materiales"
      style: docked
      
      collapse-level: 1
      contents:
        - materiales/index.qmd
        - text: "¿R?"
          href: materiales/tema01/index.qmd
        - text: "Lo Básico"
          href: materiales/tema02/index.qmd
        - text: "Importando y Explorando Datos"
          href: materiales/tema03/index.qmd
        - text: "Manipulación de Datos "
          href: materiales/tema04/index.qmd
        - text: "La Gramática de los Gráficos"
          href: materiales/tema05/index.qmd
        - text: "Personalizando y Expandiendo Gráficos"
          href: materiales/tema06/index.qmd
        - text: "Datos de Encuestas"
          href: materiales/tema07/index.qmd
        - text: "Análisis y Visualización de Datos Likert"
          href: materiales/tema08/index.qmd
        - text: "Comunicando sus Resultados con Quarto"
          href: materiales/tema09/index.qmd


format:
  html:
    css: styles.css

toc: true

lang: es

code-copy: true

code-fold: false

cache: true
       
theme:
  light: flatly
  dark: darkly

editor: source
